const images = {
  logo : "/assets/sidebar/logo.svg",
  notifcation : "/assets/sidebar/Bell.svg",
  admin : "/assets/layout/admin.png",
  dashboard: "/assets/sidebar/dashboard.svg",
  users: "/assets/sidebar/users.svg",
  chats: "/assets/sidebar/chats.svg",
  orders: "/assets/sidebar/orders.svg",
  loansDisbursement: "/assets/sidebar/loanBank.svg",
  Transections: "/assets/sidebar/transection.svg",
  Headset: "/assets/sidebar/Headset.svg",
  notification: "/assets/sidebar/notification.svg",
  referral: "/assets/sidebar/referral.svg",
  tickets: "/assets/sidebar/tickets.svg",
  analytics: "/assets/sidebar/analytics.svg",
  settings: "/assets/sidebar/settings.svg",
  logout : "/assets/sidebar/logout.svg",
  totalUsers : "/assets/dashboard/totalUsers.svg",
  Users : "/assets/dashboard/Users.svg",
  Users1 : "/assets/dashboard/Users1.svg",
  Money : "/assets/dashboard/Money.svg",
  Money1 : "/assets/dashboard/Money1.svg",
  totalOrders : "/assets/dashboard/totalOrders.svg",
  totalOrders1 : "/assets/dashboard/totalOrders1.svg",
  completeOrders : "/assets/dashboard/completeOrders.svg",
  completeOrders1 : "/assets/dashboard/completeOrders1.svg",
  MagnifyingGlass : "/assets/dashboard/MagnifyingGlass.svg",
  dots : "/assets/users/3dots.svg",
  userbackground : "/assets/users/userbackground.jpg",
  adewale : "/assets/users/adewale.png",
  edit : "/assets/users/edit.svg",
  userNotification : "/assets/users/notification.svg",
  error : "/assets/users/error.svg",
  online : "/assets/users/online.svg",
  send : "/assets/users/send.svg",
  share : "/assets/users/share.svg",
  close : "/assets/users/close.svg",
  order : "/assets/layout/order.svg",
  orderCompleted : "/assets/users/orderCompleted.svg",
  orderPending : "/assets/users/orderPending.svg",
  orderFailed : "/assets/users/orderFailed.svg",
  transection : "/assets/layout/transection.svg",
  plus : "/assets/settings/plus.svg",
  tabler : "/assets/settings/tabler.svg",
  delete : "/assets/settings/delete.svg",
  checkbox : "/assets/settings/checkbox.svg",
  paragraph : "/assets/settings/paragraph.svg",
  radiobutton : "/assets/settings/radio-button.svg",
  checkboxoutline : "/assets/settings/checkbox-outline.svg",
  add : "/assets/settings/add.svg",
  chat : "/assets/users/chat.svg",
  Notepad : "/assets/users/Notepad.svg",
  User : "/assets/users/User.svg",
  login : "/assets/login/login.png",
  logo1 : "/assets/login/logo.png",
  admin1 : "assets/users/admin.svg",
};


export default images;
